{
	"name": "Intention Error",
	"properties": {
		"description": "Used just so the ADF.procfwk has something to call during development.",
		"activities": [
			{
				"name": "Call Fail Procedure",
				"type": "SqlServerStoredProcedure",
				"dependsOn": [
					{
						"activity": "Wait1",
						"dependencyConditions": [
							"Succeeded"
						]
					}
				],
				"policy": {
					"timeout": "7.00:00:00",
					"retry": 0,
					"retryIntervalInSeconds": 30,
					"secureOutput": false,
					"secureInput": false
				},
				"userProperties": [],
				"typeProperties": {
					"storedProcedureName": "[dbo].[FailProcedure]"
				},
				"linkedServiceName": {
					"referenceName": "SupportDatabase",
					"type": "LinkedServiceReference"
				}
			},
			{
				"name": "Wait1",
				"type": "Wait",
				"dependsOn": [],
				"userProperties": [],
				"typeProperties": {
					"waitTimeInSeconds": 10
				}
			},
			{
				"name": "Call Fail Notebook",
				"type": "DatabricksNotebook",
				"dependsOn": [
					{
						"activity": "Wait1",
						"dependencyConditions": [
							"Succeeded"
						]
					}
				],
				"policy": {
					"timeout": "7.00:00:00",
					"retry": 0,
					"retryIntervalInSeconds": 30,
					"secureOutput": false,
					"secureInput": false
				},
				"userProperties": [],
				"typeProperties": {
					"notebookPath": "/Playground/Throw Exception"
				},
				"linkedServiceName": {
					"referenceName": "BricksOfData",
					"type": "LinkedServiceReference"
				}
			}
		],
		"folder": {
			"name": "Processes"
		},
		"annotations": []
	}
}